# -*- coding: utf-8 -*-
"""Excel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYWVItIuc7q-sEeZW9uzy-5j-hjYc8ud
"""

from google.colab import drive
drive.mount ('/content/gdrive/')

#Copy path file out_1.xlsx vào
path = '/content/gdrive/MyDrive/Subjects in HCMUT/221/Discrete Stuctures/Data/out_1.xlsx'
import pandas as pd
import numpy as np
import array as arr
import openpyxl
df = pd.read_excel(path, sheet_name = 'out_1')

i=0
rate=0
ratestock=[]
stock=[]
final = df.GIA[i]

while (df.index[i] <= 52814):
  if (df.Stock[i] != df.Stock[i+1]):
    first = df.GIA[i]
    rate = (final - first)/first
    final = df.GIA[i+1]
    # print(rate)
    ratestock.append(rate)
    stock.append(df.Stock[i])
  i += 1

first = df.GIA[52815]
rate = (final - first)/first
# print(rate)

ratestock.append(rate)
stock.append(df.Stock[i])

print(ratestock)
print(stock)

# tạo file ratechange trong drive
data = {'Stock': stock, 
        'Rate': ratestock}
df1 = pd.DataFrame(data, columns = ['Stock', 'Rate'])

df1.to_excel('/content/gdrive/MyDrive/Subjects in HCMUT/221/Discrete Stuctures/Data/ratechange.xlsx', sheet_name='sheet1')

j=0
k=0
temp = 0
#sắp xếp theo thứ tự giảm dần của ratechange
while (j <= 415):
  k = j+1
  while (k <= 416):
    if (ratestock[j] < ratestock[k]):
      temp = ratestock[j]
      ratestock[j] = ratestock[k]
      ratestock[k] = temp
      temp = stock[j]
      stock[j] = stock[k]
      stock[k] = temp
    k += 1
  j += 1

highestgrowth = [stock[0], stock[1], stock[2]]
strongestdrop = [stock[416], stock[415], stock[414]]
print(highestgrowth, strongestdrop)

print(stock)
print(ratestock)

# add mảng vào dataframe -> add vào file xlsx mới
data1 = {'Stock': stock, 
        'Rate': ratestock}
df2 = pd.DataFrame(data1, columns = ['Stock', 'Rate'])

df2.to_excel('/content/gdrive/MyDrive/Subjects in HCMUT/221/Discrete Stuctures/Data/rate theo thứ tự giảm dần.xlsx', sheet_name='sheet1')