# -*- coding: utf-8 -*-
"""Distribution Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LKmRJaioHjGWj2zmslx_wjKdSWg3JTAU
"""

from google.colab import drive
drive.mount ('/content/gdrive/')

!pip install pingouin

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import scipy.stats as stats

from scipy.stats import norm, kurtosis, lognorm, stats, skew
import pingouin as pg
import math
import matplotlib.pyplot as plt
# %matplotlib inline

path = '/content/gdrive/MyDrive/Subjects in HCMUT/221/Discrete Stuctures Project/Data/6stock/Title/DIG.csv'
df = pd.read_csv(path)
df = df[df['Date'] >= '01/07/2021']

df['pct'] = df['Close'].pct_change()
pct = df['pct'].to_numpy()

# print(df['Close'])

median = np.median(df['Close']) 
print(median)
mean = np.mean(df['Close'])
print(mean)
print(skew(df['Close'], bias=True))

df['Close'].describe()

df['daily_percent_change'] = df['Close'].pct_change()
df.pct.hist(figsize=(10,7))
plt.ylabel('Frequency')
plt.xlabel('Daily Percentage Change')
plt.show()

# QQ Plot
from numpy.random import seed
from numpy.random import randn
from statsmodels.graphics.gofplots import qqplot
from matplotlib import pyplot
df['pct'] = df['Close'].pct_change()
pct = df['pct'].to_numpy()
qqplot(df['pct'], line='s')
pyplot.show()